version: "3"
services:
  app:
    # image: ochanoco/proxy:latest
    # --- this is for debug
    build: ./app
    # ---
    volumes:
      - "./app:/app"
    ports:
      - 5000:5000

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/keys:/etc/nginx/conf.d/keys

  ochanoco:
    # image: ochanoco/proxy:latest
    # --- this is for debug
    build:
      context: ../ochanoco
      dockerfile: ./docker/Dockerfile
    # ---
    volumes:
      - "./ochanoco/data:/workspace/data"
      - "./ochanoco/config.yaml:/workspace/config.yaml"
    ports:
      - 8080:8080
    env_file:
      - ./ochanoco/secret.env
    environment:
      - OCHANOCO_DB_TYPE=sqlite3
      - OCHANOCO_DB_CONFIG=file:./data/db.sqlite3?_fk=1
      - LINE_LOGIN_BASE=https://127.0.0.1/ochanoco
