version: "3"
services:
  app:
    # image: ochanoco/proxy:latest
    # --- this is for debug
    build: ./app
    # ---
    volumes:
      - "./app:/app"
    ports:
      - 5000:5000
    env_file:
      - ./app/secret.env

  proxy:
    image: ghcr.io/ochanoco/proxy:develop
    volumes:
      - "./ochanoco/data:/workspace/data"
      - "./ochanoco/config.yaml:/workspace/config.yaml"
    ports:
      - 8080:8080
    env_file:
      - ./ochanoco/secret.env
    environment:
      - OCHANOCO_DB_TYPE=sqlite3
      - OCHANOCO_DB_CONFIG=file:./data/db.sqlite3?_fk=1
      - LINE_LOGIN_BASE=http://127.0.0.1:8080/ochanoco
