version: "3"
services:
  app:
    build: ./app
    volumes:
      - "./app:/app"

  proxy:
    image: ghcr.io/ochanoco/proxy:develop
    volumes:
      - "./proxy/data:/workspace/data"
      - "./proxy/config.yaml:/workspace/config.yaml"
    ports:
      - 8080:8080
    env_file:
      - ./proxy/secret.env
    environment:
      - OCHANOCO_DB_TYPE=sqlite3
      - OCHANOCO_DB_CONFIG=file:./data/db.sqlite3?_fk=1
      - OCHANOCO_BASE=http://127.0.0.1:8080/ochanoco
